Repository fredThem/Outrek, pull requests merged in 2021-04, with the labels that each got.

#93 Seeding documentation reference
  db/ref_seed.md
Labels: seeding

#95 date-time formating < Home page trips card layout
  app/views/trips/index.html.erb
Labels: frontend

#98 Mapbox static image fetching + Cloudinary upload
  Gemfile
  Gemfile.lock
  app/controllers/trips_controller.rb
  app/models/trip.rb
  app/views/trips/show.html.erb
Labels: 2 SHOULD, backend

#97 Partialize trip card and add mapbox static images
  app/controllers/trips_controller.rb
  app/views/trips/card/_display_dates.html.erb
  app/views/trips/card/_trip_card.html.erb
  app/views/trips/index.html.erb
Labels: 2 SHOULD, component, frontend

#148 Progress bar
  app/controllers/application_controller.rb
  app/controllers/duties_controller.rb
  app/controllers/trips_controller.rb
  app/models/checklist.rb
  app/policies/duty_policy.rb
  app/views/pages/_narrow_col.html.erb
  app/views/trips/_trip_index.html.erb
  app/views/trips/card/_trip_card.html.erb
  app/views/trips/show.html.erb
  config/routes.rb
Labels: 3 COULD, backend, bug
